### PR TITLE
pkg/cli/image/extract: disable pigz to prevent race condition

### LINKED ISSUE #58: "panic: runtime error: slice bounds out of range" while "oc adm release extract"
**Describe the bug**
Just running a `make` within the https://github.com/openshift-metal3/dev-scripts/ with my usual hardware/environment 

**To Reproduce**
From dev-scripts  b37f69396 commit, RHEL8 helper node

**Expected/observed behavior**
```
+ oc adm release extract --registry-config installer--q65IkgS0h2/pullsecret --command=openshift-install --to installer--q65IkgS0h2 registry.svc.ci.openshift.org/kni/release:4.2.0-0.ci-2019-07-31-123929-kni.0
panic: runtime error: slice bounds out of range

goroutine 163 [running]:
bufio.(*Reader).fill(0xc000f35c80)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/bufio/bufio.go:89 +0x211
bufio.(*Reader).WriteTo(0xc000f35c80, 0x2dfa380, 0xc000010838, 0x7f60a71fde08, 0xc000f35c80, 0x1)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/bufio/bufio.go:511 +0x106
io.copyBuffer(0x2dfa380, 0xc000010838, 0x2df4f60, 0xc000f35c80, 0x0, 0x0, 0x0, 0xc0013e5260, 0xc0000edb00, 0x0)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/io/io.go:384 +0x34e
io.Copy(...)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/io/io.go:364
os/exec.(*Cmd).stdin.func1(0xc000ef4900, 0x0)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/os/exec/exec.go:243 +0x67
os/exec.(*Cmd).Start.func1(0xc0008f34a0, 0xc0014f7680)
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/os/exec/exec.go:409 +0x27
created by os/exec.(*Cmd).Start
        /opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/os/exec/exec.go:408 +0x58f
make: *** [Makefile:21: ocp_run] Error 2
```

**Additional context**
Trying again seems to work and I've not been able to reproduce it.

Reported first here https://github.com/openshift-metal3/dev-scripts/issues/734

### PR DESCRIPTION
**Pull request by stbenjam**
There is a race condition in the vendored version of docker code that
can cause image extraction to panic.  When the `pigz` package is
installed, docker's DecompressStream code prefers to use it, however,
that code can return the io buffer to the pool while the command is
still writing to it. If the buffer is reused while that's happening,
`oc` will panic.  There are many reports of this happening.

As the vendored docker comes from kubectl, and the version there (even
for k8s 1.16) is quite old, this disables using pigz at all by setting
MOBY_DISABLE_PIGZ environment variable. 

fixes #58

### CODE REVIEW

File: pkg/cli/image/extract/extract.go [hunk 1]
```diff
@@ -483,6 +483,10 @@ func (o *Options) Run() error {
 }
 
 func layerByEntry(r io.Reader, options *archive.TarOptions, layerInfo LayerInfo, fn TarEntryFunc, allLayers bool, alreadySeen map[string]struct{}) (bool, error) {
+	// Prevents race condition present in vendored version of docker
+	// https://github.com/moby/moby/issues/39859
+	os.Setenv("MOBY_DISABLE_PIGZ", "true")
```
Comment (cgwalters) [inline pkg/cli/image/extract/extract.go]: This may introduce *new* race conditions; changing the environment in a multi-threaded process can create undefined behavior; see:

https://github.com/rust-lang/rust/pull/24741

Comment (stbenjam) [reply pkg/cli/image/extract/extract.go]: The situation is certainly better with this fix that it was before this, the panics were unbearable. Would a mutex around this be sufficient to mitigate the risk or is that not sufficient?

Comment (cgwalters) [reply pkg/cli/image/extract/extract.go]: From a quick look, golang has [a mutex around os.{G,S}etenv](https://github.com/golang/go/blob/a38a917aee626a9b9d5ce2b93964f586bf759ea0/src/syscall/env_unix.go#L18) - so if there's no C threads running, it's generally OK.

But, it'd be safer to hoist this to early in `main()`.
